import { Product } from '../types';

export const MOCK_PRODUCTS: Product[] = [
  // --- Gaming Laptops ---
  {
    id: 1,
    itemCode: 'MSI-GE78',
    name: 'MSI Raider GE78 HX',
    brand: 'MSI',
    category: 'Laptops',
    subCategory: 'Gaming Laptops',
    price: 1828200,
    originalPrice: 2050000,
    discount: '11% OFF',
    specs: 'Intel i9-13980HX, 32GB DDR5, RTX 4090 16GB, 2TB NVMe SSD, 17" QHD+ 240Hz',
    image: '/images/images.jpg',
    badge: 'PRE ORDER',
    stock: 5,
    rating: 4.9,
    reviewCount: 14
  },
  {
    id: 2,
    itemCode: 'MSI-GE68',
    name: 'MSI Raider GE68 HX',
    brand: 'MSI',
    category: 'Laptops',
    subCategory: 'Gaming Laptops',
    price: 1966800,
    originalPrice: 2200000,
    discount: '11% OFF',
    specs: 'Intel i9-13950HX, 32GB DDR5, RTX 4080 12GB, 2TB SSD, 16" QHD+ 240Hz',
    image: '/images/blk_sitewide_400x400.webp',
    badge: 'PRE ORDER',
    stock: 8,
    rating: 4.8,
    reviewCount: 9
  },
  {
    id: 3,
    itemCode: 'MSI-TITAN-18',
    name: 'MSI Titan 18 HX AI',
    brand: 'MSI',
    category: 'Laptops',
    subCategory: 'Gaming Laptops',
    price: 2557500,
    originalPrice: 2850000,
    discount: '10% OFF',
    specs: 'Intel i9-14900HX, 64GB DDR5, RTX 4090 16GB, 4TB SSD, 18" 4K Mini-LED 120Hz',
    image: '/images/images.jpg',
    badge: 'FLAGSHIP',
    stock: 3,
    rating: 5.0,
    reviewCount: 6
  },
  {
    id: 4,
    itemCode: 'ROG-G18',
    name: 'ASUS ROG Strix G18',
    brand: 'ASUS',
    category: 'Laptops',
    subCategory: 'Gaming Laptops',
    price: 1750000,
    originalPrice: 1950000,
    discount: '10% OFF',
    specs: 'Intel i9-13980HX, 32GB DDR5, RTX 4070 Ti, 1TB NVMe, 18" Nebula Display 240Hz',
    image: '/images/blk_sitewide_400x400.webp',
    badge: 'NEW',
    stock: 12,
    rating: 4.7,
    reviewCount: 18
  },
  {
    id: 5,
    itemCode: 'LEN-LEGION-9',
    name: 'Lenovo Legion 9i Gen 8',
    brand: 'Lenovo',
    category: 'Laptops',
    subCategory: 'Gaming Laptops',
    price: 2350000,
    originalPrice: 2600000,
    discount: '10% OFF',
    specs: 'Intel i9-13980HX, 32GB DDR5, RTX 4090, 2TB SSD, Liquid Cooled Carbon Fiber',
    image: '/images/images (1).jpg',
    badge: 'HOT',
    stock: 4,
    rating: 4.9,
    reviewCount: 11
  },
  {
    id: 6,
    itemCode: 'HP-OMEN-16',
    name: 'HP Omen 16 Gaming',
    brand: 'HP',
    category: 'Laptops',
    subCategory: 'Gaming Laptops',
    price: 685000,
    originalPrice: 750000,
    discount: '9% OFF',
    specs: 'AMD Ryzen 7 7840HS, 16GB DDR5, RTX 4060 8GB, 1TB SSD, 16.1" 165Hz',
    image: '/images/images (2).jpg',
    badge: 'POPULAR',
    stock: 15,
    rating: 4.6,
    reviewCount: 22
  },

  // --- Ultrabooks & Business ---
  {
    id: 7,
    itemCode: 'APPLE-MBP-M3M',
    name: 'Apple MacBook Pro 16" M3 Max',
    brand: 'Apple',
    category: 'Laptops',
    subCategory: 'Business Laptops',
    price: 1650000,
    originalPrice: 1800000,
    discount: '8% OFF',
    specs: 'Apple M3 Max (16-core CPU, 40-core GPU), 36GB Unified Memory, 1TB SSD, Space Black',
    image: '/images/images (3).jpg',
    badge: 'BESTSELLER',
    stock: 7,
    rating: 5.0,
    reviewCount: 31
  },
  {
    id: 8,
    itemCode: 'DELL-XPS-15',
    name: 'Dell XPS 15 9530 OLED',
    brand: 'Dell',
    category: 'Laptops',
    subCategory: 'Ultrabooks',
    price: 890000,
    originalPrice: 990000,
    discount: '10% OFF',
    specs: 'Intel Core i7-13700H, 32GB DDR5, RTX 4060, 1TB SSD, 15.6" 3.5K OLED Touch',
    image: '/images/images (4).jpg',
    badge: 'PRO',
    stock: 6,
    rating: 4.8,
    reviewCount: 15
  },

  // --- Desktops & Workstations ---
  {
    id: 9,
    itemCode: 'DESK-QC-TITAN',
    name: 'Quantum Core Titan Ultra Desktop',
    brand: 'Custom PC',
    category: 'Computers',
    subCategory: 'Gaming Desktops',
    price: 1950000,
    originalPrice: 2200000,
    discount: '11% OFF',
    specs: 'Intel i9-14900K, Custom Loop Watercooling, 64GB DDR5 6400MHz, RTX 4090 24GB, 4TB Gen5 SSD',
    image: '/images/WORKSTATION AND GAMING DESKTOP.png',
    badge: 'CUSTOM BUILD',
    stock: 3,
    rating: 5.0,
    reviewCount: 8
  },
  {
    id: 10,
    itemCode: 'DESK-QC-PRO',
    name: 'Quantum Core Creator Workstation',
    brand: 'Custom PC',
    category: 'Computers',
    subCategory: 'Workstations',
    price: 1450000,
    originalPrice: 1650000,
    discount: '12% OFF',
    specs: 'AMD Threadripper 7960X 24-Core, 128GB DDR5 ECC, NVIDIA RTX A5000 24GB, 4TB NVMe',
    image: '/images/DESKTOP AND ACCESORIES copy.png',
    badge: 'WORKSTATION',
    stock: 2,
    rating: 4.9,
    reviewCount: 5
  },

  // --- Accessories & Components ---
  {
    id: 11,
    itemCode: 'COR-VENG-DDR5-32',
    name: 'Corsair Vengeance DDR5 32GB (2x16GB)',
    brand: 'Corsair',
    category: 'Accessories',
    subCategory: 'Memory & Storage',
    price: 38500,
    originalPrice: 45000,
    discount: '14% OFF',
    specs: '6000MHz CL36 Intel XMP 3.0 & AMD EXPO High Speed Gaming RAM',
    image: '/images/images (5).jpg',
    stock: 40,
    rating: 4.9,
    reviewCount: 45
  },
  {
    id: 12,
    itemCode: 'SAM-990-PRO-2TB',
    name: 'Samsung 990 PRO NVMe M.2 2TB SSD',
    brand: 'Samsung',
    category: 'Accessories',
    subCategory: 'Memory & Storage',
    price: 74500,
    originalPrice: 85000,
    discount: '12% OFF',
    specs: 'PCIe 4.0 NVMe, Sequential Read up to 7450 MB/s, Heatsink Edition',
    image: '/images/images (6).jpg',
    badge: 'BESTSELLER',
    stock: 28,
    rating: 5.0,
    reviewCount: 58
  },
  {
    id: 13,
    itemCode: 'LOGI-G-PRO-X',
    name: 'Logitech G PRO X Superlight 2 Wireless',
    brand: 'Logitech',
    category: 'Accessories',
    subCategory: 'Peripherals',
    price: 49500,
    originalPrice: 56000,
    discount: '11% OFF',
    specs: 'HERO 2 Sensor 32K DPI, 60g Ultralight, LIGHTSPEED Wireless 2K Polling',
    image: '/images/images (7).jpg',
    badge: 'ESPORTS',
    stock: 19,
    rating: 4.8,
    reviewCount: 39
  },
  {
    id: 14,
    itemCode: 'ASUS-ROG-SWIFT-27',
    name: 'ASUS ROG Swift OLED PG27AQDM 27"',
    brand: 'ASUS',
    category: 'Accessories',
    subCategory: 'Monitors',
    price: 395000,
    originalPrice: 440000,
    discount: '10% OFF',
    specs: '27-inch 1440p OLED, 240Hz, 0.03ms Response, 99% DCI-P3, HDR1000',
    image: '/images/images (8).jpg',
    badge: 'OLED',
    stock: 8,
    rating: 4.9,
    reviewCount: 16
  }
];

export const CATEGORIES = [
  { name: 'All', slug: 'all' },
  { name: 'Laptops', slug: 'laptops', image: '/images/GAMING LAPTOPS.png' },
  { name: 'Computers', slug: 'computers', image: '/images/WORKSTATION AND GAMING DESKTOP.png' },
  { name: 'Accessories', slug: 'accessories', image: '/images/LAPTOP ACCESORIES copy.png' }
];

export const BRANDS = ['All', 'MSI', 'ASUS', 'Apple', 'Lenovo', 'HP', 'Dell', 'Samsung', 'Corsair', 'Logitech'];
